"""empty message

Revision ID: b5b4bdd5a501
Revises: 5a58883cdcec
Create Date: 2023-05-12 23:56:03.643197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b4bdd5a501'
down_revision = '5a58883cdcec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.String(length=200), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('desc')

    # ### end Alembic commands ###
